<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>Musify.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="DispatchR.Mediator" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="X.PagedList" Version="10.5.9" />
    <PackageReference Include="X.PagedList.EF" Version="10.5.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Musify.Backend\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="Contracts\Application\" />
    <Folder Include="PlayLists\Commands\CreatePlayList\" />
    <Folder Include="PlayLists\Commands\DeletePlayList\" />
    <Folder Include="PlayLists\Commands\UpdatePlayList\" />
  </ItemGroup>

</Project>
