<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1c3fa41c-6f07-433b-af79-1f67fad338fd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.19" />
    <PackageReference Include="Keycloak.Net.Core" Version="1.0.38" />
    <PackageReference Include="MassTransit" Version="9.0.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.0.1" />
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="OpenTelemetry" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Api.ProviderBuilderExtensions" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.11" />
    <PackageReference Include="X.PagedList.EF" Version="10.5.9" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Application">
      <HintPath>..\..\MusifyBackend\Infrastructure\bin\Debug\net10.0\Application.dll</HintPath>
    </Reference>
    <Reference Include="Domain">
      <HintPath>..\..\MusifyBackend\Infrastructure\bin\Debug\net10.0\Domain.dll</HintPath>
    </Reference>
    <Reference Include="Infrastructure">
      <HintPath>..\..\MusifyBackend\Infrastructure\bin\Debug\net10.0\Infrastructure.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
