<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PictureWorker-1dfff89f-0602-41b7-8eaf-4da2c3358789</UserSecretsId>
    <RootNamespace>Musify.Worker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.23.4" />
    <PackageReference Include="DispatchR.Mediator" Version="2.2.0" />
    <PackageReference Include="MassTransit" Version="8.5.9" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.8" />
    <PackageReference Include="MimeMapping" Version="4.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MusifyBackend\Application\Application.csproj" />
    <ProjectReference Include="..\..\MusifyBackend\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\MusifyBackend\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>
</Project>
